#!/usr/bin/env python2.7
import os;CWD = os.path.abspath(os.path.dirname(__file__))

import sys; sys.path.append(os.path.join(CWD, 'vendor'))

from nikola.__main__ import main

main(sys.argv[1:])

import commands
print commands.getstatusoutput('chmod 711 output')
print commands.getstatusoutput('chmod 711 output/cgi')
